### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by l4u** [foliveira/jscs-fixer#2]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.190.0
**System**: Mac OS X 10.10.2
**Thrown From**: [jscs-fixer](https://github.com/foliveira/jscs-fixer) package, v0.2.4
### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/Leo/.atom/packages/jscs-fixer/lib/jscsfixer.js:14

TypeError: undefined is not a function
  at atom-workspace.toggle (/Users/Leo/.atom/packages/jscs-fixer/lib/jscsfixer.js:14:25)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/command-registry.js:242:29)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:120:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/command-registry.js:242:29)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:521:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:356:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/window-event-handler.js:180:20)

```
### Commands

```
     -0:04.7 command-palette:toggle (atom-text-editor.editor.vim-mode.command-mode)
  2x -0:03.1 core:backspace (atom-text-editor.editor.mini)
     -0:02.5 core:confirm (atom-text-editor.editor.mini)
     -0:02.5 jscs-fixer:fix (atom-text-editor.editor.vim-mode.command-mode)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ],
    "disabledPackages": [
      "minimap",
      "jshint",
      "highlight-line",
      "autocomplete-clang",
      "atom-lint",
      "linter-jshint"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-typescript, v2.14.0
autoclose-html, v0.15.0
autocomplete-css, v0.6.0
autocomplete-html, v0.5.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.9.0
autocomplete-snippets, v1.2.0
color-picker, v1.6.0
file-icons, v1.5.3
git-log, v0.3.0
git-projects, v1.13.0
git-tab-status, v1.6.0
highlight-selected, v0.9.1
javascript-snippets, v1.0.0
jscs-fixer, v0.2.4
jsformat, v0.7.18
language-SCSS, v0.2.0
language-elixir, v0.4.0
language-erlang, v2.0.0
language-haml, v0.17.0
language-swift, v0.3.0
linter, v0.12.0
linter-coffeelint, v0.2.1
linter-csslint, v0.0.11
linter-elixirc, v0.2.1
linter-erlc, v0.2.0
linter-flow, v0.1.4
linter-haml, v0.1.1
linter-hlint, v0.3.1
linter-js-yaml, v1.0.0
linter-jscs, v1.10.0
linter-less, v0.3.1
linter-rubocop, v0.2.2
linter-ruby, v0.1.4
linter-scss-lint, v0.0.14
linter-swiftc, v0.2.2
linter-tslint, v0.2.1
markdown-format, v2.5.0
meteor-api, v2.12.0
open-last-project, v0.3.5
permute, v0.1.0
pretty-json, v0.3.2
project-manager, v1.15.5
react, v0.11.2
script, v2.18.0
tabs-to-spaces, v0.9.2
text-manipulation, v0.4.0
vim-mode, v0.43.0
wakatime, v4.0.1

# Dev
No dev packages
```

**Comment by foliveira** [comment]
Hi @l4u!

It seems that `jscs-fixer` was invoked when no file was opened. It's a known issue and it will be fixed.

If that wasn't the case can you provide some more info?

Thanks for reporting :+1:

**Comment by l4u** [comment]
Thanks! I've opened a js file when invoking the jscs fixer command.

**Comment by foliveira** [comment]
@l4u it was due to a mislabeled variable. It should be fixed now
