### ISSUE TITLE
Uncaught TypeError: Arguments to path.join must be strings

### ISSUE THREAD

**Issue by foliveira** [foliveira/jscs-fixer#4]
[Enter steps to reproduce below:]
1. Try to fix a file

**Atom Version**: 0.190.0
**System**: Mac OS X 10.10.3
**Thrown From**: [jscs-fixer](https://github.com/foliveira/jscs-fixer) package, v0.2.7
### Stack Trace

Uncaught TypeError: Arguments to path.join must be strings

```
At path.js:449

TypeError: Arguments to path.join must be strings
  at Object.posix.join (path.js:449:13)
  at atom-workspace.toggle (/Users/foliveira/.atom/packages/jscs-fixer/lib/jscsfixer.js:18:25)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/command-registry.js:242:29)
  at CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/command-registry.js:157:19)
  at [object Object].jQuery.fn.trigger (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:64:23)
  at EventEmitter.<anonymous> (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/window-event-handler.js:78:67)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:169:7)
  at EventEmitter.ipc.sendSync (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:110:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/context-menu-manager.js:168:31)
  at HTMLDocument.<anonymous> (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/window-event-handler.js:151:33)
  at HTMLDocument.handler (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)

```
### Commands

```
     -0:05.7 fuzzy-finder:toggle-file-finder (atom-text-editor.editor)
     -0:04.6 core:confirm (atom-text-editor.editor.mini)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "metrics",
      "autosave",
      "deprecation-cop",
      "language-objective-c",
      "welcome",
      "language-clojure",
      "language-java",
      "language-perl",
      "language-php",
      "language-python",
      "language-ruby",
      "language-ruby-on-rails",
      "language-sql",
      "language-toml",
      "language-csharp",
      "jshint",
      "linter-js-standard"
    ],
    "themes": [
      "unity-ui",
      "monokai"
    ],
    "projectHome": "/Users/foliveira/Projects"
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-plus, v2.9.0
compare-files, v0.4.1
editorconfig, v0.3.3
fonts, v0.4.2
jscs-fixer, v0.2.7
language-elixir, v0.4.0
linter, v0.12.0
linter-jscs, v1.10.0
monokai, v0.14.0
unity-ui, v2.0.5

# Dev
No dev packages
```

**Comment by foliveira** [comment]
Fixed with 23607e6
